FROM centos

RUN  yum upgrade -y && \
     yum -y install procps openssh-server && \
     systemctl enable sshd && \
     yum -y clean all

RUN echo 'root:root' | chpasswd
RUN sed -i 's/#*PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd

ENV NOTVISIBLE="in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

RUN rm /run/nologin

EXPOSE 22
CMD ["/sbin/init"]
